FROM ghcr.io/pnpm/pnpm:11.8.0

RUN pnpm runtime set node 24.17.0 -g

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD [ "pnpm", "dev" ]

EXPOSE 8080